name: test
on: [push, pull_request, workflow_dispatch]
jobs:
  Test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - name: npm run setup
      - run: npm run setup
      - name: npm run test
      - run: npm run test
